import subprocess
import sys
import os

def run_git_command(command):
    try:
        return subprocess.check_output(command, text=True, stderr=subprocess.STDOUT).strip()
    except subprocess.CalledProcessError as e:
        print(f"Error running git command {' '.join(command)}: {e.output}")
        return None

def categorize_changes(diff_stat, commit_logs):
    categories = {
        "🚀 Features": [],
        "🐛 Bug Fixes": [],
        "🏗️ Refactoring": [],
        "🌍 Localization": [],
        "📝 Documentation": [],
        "📦 Other": []
    }
    
    # Simple categorization based on commit messages
    for log in commit_logs.split('\n'):
        if not log: continue
        msg = log.lower()
        if any(keyword in msg for keyword in ['feat', 'add', 'new']):
            categories["🚀 Features"].append(log)
        elif any(keyword in msg for keyword in ['fix', 'bug', 'resolve']):
            categories["🐛 Bug Fixes"].append(log)
        elif any(keyword in msg for keyword in ['refactor', 'clean', 'structure']):
            categories["🏗️ Refactoring"].append(log)
        elif any(keyword in msg for keyword in ['loc', 'translate', '.po', 'translation']):
            categories["🌍 Localization"].append(log)
        elif any(keyword in msg for keyword in ['doc', 'readme', 'manual']):
            categories["📝 Documentation"].append(log)
        else:
            categories["📦 Other"].append(log)
            
    return categories

def generate_report(ref1, ref2, output_file="COMPARISON_REPORT.md"):
    print(f"Comparing {ref1} to {ref2}...")
    
    diff_stat = run_git_command(['git', 'diff', f'{ref1}..{ref2}', '--stat'])
    commit_logs = run_git_command(['git', 'log', f'{ref1}..{ref2}', '--oneline'])
    
    if diff_stat is None or commit_logs is None:
        print("Failed to retrieve git information.")
        return

    categories = categorize_changes(diff_stat, commit_logs)
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(f"# Comparison Report: {ref1} vs {ref2}\n\n")
        f.write("## 📊 File Statistics\n```text\n")
        f.write(diff_stat)
        f.write("\n```\n\n")
        
        f.write("## 🛠️ Changes by Category\n\n")
        for cat, items in categories.items():
            if items:
                f.write(f"### {cat}\n")
                for item in items:
                    f.write(f"- {item}\n")
                f.write("\n")
        
        f.write("---\n*Generated by scripts/compare_commits.py*")

    print(f"Report generated: {output_file}")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python scripts/compare_commits.py <ref1> <ref2> [output_file]")
        sys.exit(1)
    
    ref1 = sys.argv[1]
    ref2 = sys.argv[2]
    out = sys.argv[3] if len(sys.argv) > 3 else "COMPARISON_REPORT.md"
    
    generate_report(ref1, ref2, out)
